figmaの社員一覧画面作成
MyztKnt/next-storybook-for-beginners pull request #12
Opened 2024-08-13 02:40 UTC by MyztKnt

下記タスクの実装完了しました。

figmaの社員一覧画面作成

Storybookで表示できている事を確認しています。
ご確認のほどよろしくお願い致します。

2024-08-13 03:44 UTC, fox-Taisei-Nakamura requested changes

2024-08-13 03:44 UTC, fox-Taisei-Nakamura commented on app/employee/employeelist.stories.tsx
> +  parameters: {
storybookファイルでモックデータを記載するようにしてください

2024-08-13 03:44 UTC, fox-Taisei-Nakamura commented on app/employee/employeelist.tsx
> +const employees: Employee[] = [
page.tsxでAPIからデータを取得するようにしてください

2024-08-13 03:44 UTC, fox-Taisei-Nakamura commented on app/employee/page.tsx
> +    <div className="container mx-auto p-4">
dashboard/page.tsxを参考にAPIからデータの取得を行える等に修正してください

2024-08-13 03:44 UTC, fox-Taisei-Nakamura commented on app/employee/types.ts
> +export interface Employee {
`pnpm document`でモックAPIのドキュメントを開き、型で意義の修正を行ってください

2024-08-13 03:44 UTC, fox-Taisei-Nakamura commented on app/employee/employeelist.tsx
> +                        <Box ml={2}>{partner.name}</Box>
xsやmlはMUIの独自のスタイル適応の方法のため、できるだけTailwindを使ってスタイルを当てるようにしてください

2024-08-14 01:59 UTC, MyztKnt commented
下記の修正完了致しましたので、ご確認お願い致します。
・storybookファイルでモックデータを記載
・page.tsxでAPIからデータを取得
・pnpm documentでモックAPIのドキュメントを確認し、型を定義

2024-08-14 09:22 UTC, fox-Taisei-Nakamura requested changes

2024-08-14 09:22 UTC, fox-Taisei-Nakamura commented on app/employee/employeelist.tsx
> +const colors = ['#FF5733', '#33FF57', '#3357FF', '#FF33A1', '#A133FF'];
不要なら削除してください

2024-08-14 09:22 UTC, fox-Taisei-Nakamura commented on app/employee/page.tsx
> +  return <EmployeeList employees={employees} partners={partners} />;
不要になった`console.log`は削除して下さい

2024-08-14 11:07 UTC, MyztKnt commented on app/employee/employeelist.stories.tsx
> +  parameters: {
storybookファイルでモックデータを記載しました。

2024-08-14 11:07 UTC, MyztKnt commented on app/employee/employeelist.tsx
> +const employees: Employee[] = [
page.tsxでAPIからデータを取得するようにしました。

2024-08-14 11:08 UTC, MyztKnt commented on app/employee/page.tsx
> +    <div className="container mx-auto p-4">
dashboard/page.tsxを参考にAPIからのデータ取得しました。ご助言ありがとうございます。

2024-08-14 11:10 UTC, MyztKnt commented on app/employee/types.ts
> +export interface Employee {
app\employee\types.tsで型定義行いました。

2024-08-14 11:11 UTC, MyztKnt commented on app/employee/employeelist.tsx
> +                        <Box ml={2}>{partner.name}</Box>
xsやmlをTailwindへ変更しました。

2024-08-14 11:43 UTC, fox-Taisei-Nakamura requested changes

2024-08-14 11:43 UTC, fox-Taisei-Nakamura commented on app/employee/employeelist.tsx
> +            <Table>
1行に高さがFigmaより大きいため調整してください
`size=small`

2024-08-14 11:44 UTC, fox-Taisei-Nakamura requested changes

2024-08-14 11:44 UTC, fox-Taisei-Nakamura commented on app/employee/employeelist.tsx
> +            <Table>
1行に高さがFigmaより大きいため調整してください
`size=small`

2024-08-14 11:50 UTC, MyztKnt commented on app/employee/employeelist.tsx
> +const colors = ['#FF5733', '#33FF57', '#3357FF', '#FF33A1', '#A133FF'];
こちらは、Avatarの色を分けるのに使用しています。

2024-08-14 11:52 UTC, MyztKnt commented on app/employee/page.tsx
> +  return <EmployeeList employees={employees} partners={partners} />;
console.log削除しました。

2024-08-14 12:24 UTC, MyztKnt commented on app/employee/employeelist.tsx
> +            <Table>
ご助言頂いた、size=smallを<Table size="small">と、<Button size="small" variant="outlined">へ適用しました。

2024-08-14 12:25 UTC, MyztKnt commented on app/employee/employeelist.tsx
> +            <Table>
ご助言頂いた、　size=small　を　Table size="small"　と、　Button size="small" variant="outlined"　へ適用しました。

2024-08-14 12:28 UTC, MyztKnt commented
レビュー頂いた内容修正しました。ご確認お願いします。
const colors = ['#FF5733', '#33FF57', '#3357FF', '#FF33A1', '#A133FF'];
こちらは、Avatarの色を分けるのに使用している為、そのまま残しています。
ご助言頂いた、　size=small　を　Table size="small"　と、　Button size="small" variant="outlined"　へ適用（社員一覧、協力会社一覧共に）しました。

2024-08-15 09:17 UTC, fox-Taisei-Nakamura approved these changes

2024-08-15 09:18 UTC, merged