figmaの工数集計画面の作成
MyztKnt/next-storybook-for-beginners pull request #16
Opened 2024-08-14 09:21 UTC by MyztKnt

下記タスクの実装完了しました。

figmaの工数集計画面の作成

Storybook及びdevでの表示できている事を確認しています。
ご確認のほどよろしくお願い致します。

2024-08-14 12:10 UTC, fox-Taisei-Nakamura requested changes

2024-08-14 12:10 UTC, fox-Taisei-Nakamura commented on app/aggregatemanhour/page.tsx
> +  console.log(aggregatemanhours);
不要なconsoleログは削除してください

2024-08-14 12:10 UTC, fox-Taisei-Nakamura commented on app/aggregatemanhour/page.tsx
> +  const date = '2024-04-01';
この`date`だと、2024-04-01のデータしか取得できないため以下に変更してください
```
const date = new Date()
    .toLocaleDateString('ja-JP', { year: 'numeric', month: '2-digit', day: '2-digit' })
    .replaceAll('/', '-');
```

2024-08-14 12:10 UTC, fox-Taisei-Nakamura commented on app/aggregatemanhour/aggregatemanhour.tsx
> +        </select>
以下の処理で年を取得しています。
必要に応じてマイナスで年を調整してください
```
const currentYear = new Date().getFullYear();
```

2024-08-15 05:40 UTC, MyztKnt commented on app/aggregatemanhour/page.tsx
> +  console.log(aggregatemanhours);
console.log削除しました。

2024-08-15 05:41 UTC, MyztKnt commented on app/aggregatemanhour/page.tsx
> +  const date = '2024-04-01';
頂いたコードで、dateを動的に変更しました。

2024-08-15 05:43 UTC, MyztKnt commented on app/aggregatemanhour/aggregatemanhour.tsx
> +        </select>
頂いたコードで、yearを動的に変更しました。
forを使用して現在から過去5年リストに出るようにしました。

2024-08-15 05:51 UTC, MyztKnt commented
ご指示頂きました、下記の修正完了致しました。ご確認お願い致します。
・不要なconsoleログを削除
・頂いたコードを利用し、dateを動的に変更
・頂いたコードを利用し、yearを動的に変更（forを使用して現在から過去5年リストに出力）

2024-08-15 10:13 UTC, fox-Taisei-Nakamura commented
![スクリーンショット 2024-08-15 190958](https://github.com/user-attachments/assets/9fc5a9ee-6352-475d-8807-3b74d7f030b8)
一覧の各項目を等間隔ではなく、Figmaデザインのように調整してください
日時は150px
工数は110px
総工数は80pxになっています

2024-08-15 10:14 UTC, fox-Taisei-Nakamura requested changes

2024-08-15 10:14 UTC, fox-Taisei-Nakamura commented on app/aggregatemanhour/aggregatemanhour.tsx
> +              </TableRow>
等間隔ではなく、正しく幅を指定してください

2024-08-16 03:46 UTC, MyztKnt commented on app/aggregatemanhour/aggregatemanhour.tsx
> +              </TableRow>
ご指示頂いたように、下記修正しました。
現場開始日時、現場最終日時は150pxに設定。
対象月の工数は110pxに設定。
総工数は80pxに設定。

2024-08-16 03:51 UTC, MyztKnt commented
ご指示頂きました、下記の修正完了致しました。ご確認お願い致します。
・セル幅を固定値指定部分を固定幅へ設定。
・日付が”-”となっていたのを”/”へ変更。

2024-08-16 05:11 UTC, fox-Taisei-Nakamura approved these changes

2024-08-16 05:38 UTC, merged